Resources:
  K8sLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: k8s-lambda-layer
      Description: My Lambda Layer
      Content:
        S3Bucket: !Sub lambda-code-bucket-${AWS::AccountId}-${AWS::Region}
        S3Key: k8s-layer.zip
      CompatibleRuntimes:
        - python3.13
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: restart-eks-deployment
      Role: !ImportValue LambdaEKSAccessRoleArn
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      Timeout: 900
      Code:
        S3Bucket: !Sub lambda-code-bucket-${AWS::AccountId}-${AWS::Region}
        S3Key: restart.zip
      Layers: 
        - !Ref K8sLambdaLayer