Parameters:
  EnvironmentName:
    Type: String
  VpcCIDR:
    Type: String
    Default: 10.192.0.0/16
Resources:
  EksVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Ref EnvironmentName 
